### ISSUE TITLE
Editi command cannot remove the date of internship

### ISSUE THREAD

**Issue by ish1506** [AY2223S1-CS2103T-F11-1/tp#112]
Once the `Internship` has an existing `interviewDate`, `editi` cannot be used to remove that date.

**Comment by chengda300** [comment]
Upon further analysis,
the current edit*Command creates a separate Person/Internship that is initially null for all fields, which is populated by the new versions, then the "edit" part only takes in whatever that is not null (the ones that are intended to be edited)
So if it is intended to be set to null, the command actually ignores it, thinking that there is no change to that field.
