### ISSUE TITLE
Update the DG (User stories and Use cases)

### ISSUE THREAD

**Issue by nqt230** [AY2223S1-CS2103T-F11-1/tp#12]
Add the following to the DG, based on your project notes from the previous weeks. Some examples of these can be found in the [AB3 Developer Guide](https://se-education.org/addressbook-level3/DeveloperGuide.html#product-scope).
- Target user profile, value proposition, and user stories: Update the target user profile and value proposition to match the project direction you have selected. Give a list of the user stories (and update/delete existing ones, if applicable), including priorities. This can include user stories considered but will not be included in the final product.
- Use cases: Give use cases (textual form) for a few representative user stories that need multiple steps to complete. e.g. Adding a tag to a person (assume the user needs to find the person first)
- Non-functional requirements: Note: Many of the given project constraints can be considered NFRs. You can add more. e.g. performance requirements, usability requirements, scalability requirements, etc.
- Glossary: Define terms that are worth recording.

The above DG sections should cover the full requirements of the product, some of which might not get implemented by the end of this semester. Furthermore, these sections will be graded at the final project evaluation, and any bugs in the content can cost you marks at that point.

Problems in User Stories. Examples:
- Incorrect format
- All three parts are not present
- The three parts do not match with each other
- Important user stories missing 

Problems in Use Cases. Examples:
- Important use cases missing (a use case is important if it involves a user interaction that is worthy of documenting e.g., it has multiple extensions -- this is not the same as the feature being important)
- Formatting/notational errors
- Incorrect step numbering
- Unnecessary UI details mentioned
- Missing/unnecessary steps
- Missing extensions 

Problems in NFRs. Examples:
- Not really a Non-Functional Requirement
- Not scoped clearly (i.e., hard to decide when it has been met)
- Not reasonably achievable
- Highly relevant NFRs missing 

Problems in Glossary. Examples:
- Unnecessary terms included
- Important terms missing

**Comment by chengda300** [comment]
Will complete this during v1.2
As of now, the workload distribution is quite uneven so we will readjust the workload planning, since we did not really plan out the workload for the actual coding of each enhancement/feature yet.
