### ISSUE TITLE
[PE-D][Tester C] Invalid phone numbers accepted as input

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-F11-1/tp#206]
Invalid phone numbers such as 12345678 (numbers that don't start with 8 or 9), are also accepted by the system, even though they may not be appropriate inputs (in a local context).

![image.png](https://raw.githubusercontent.com/nealetham/ped/main/files/943dcdcc-4086-484b-922d-61f379af6b1c.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: nealetham/ped#2

**Comment by ish1506** [comment]
TODO: Specify constraints in UG for phone number
