### ISSUE TITLE
[PE-D][Tester D] Cannot edit Person to have the same name as another Person in list 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-F11-1/tp#222]
![Screenshot (271).png](https://raw.githubusercontent.com/qiaoen17/ped/main/files/97684746-a626-4b10-9609-94deb44ee33a.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: qiaoen17/ped#4

**Comment by tanxuanyun** [comment]
TODO: State cannot allow duplicate name in edit command
