### ISSUE TITLE
[PE-D][Tester C] No errors when adding a new person to link to an already occupied internship

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-F11-1/tp#228]
Trying to link two contact persons to the same internship would display that it is not possible to do so. 

But if I were to create a new Person, and link it to the same already occupied internship, no errors are thrown.

Though the newly created Person would not have any linked company/internships. You could potentially throw a warning over here to tell the user that the internship is already occupied.

![image.png](https://raw.githubusercontent.com/nealetham/ped/main/files/88956610-189b-4e93-9ff6-c069292ab687.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: nealetham/ped#8

**Comment by chengda300** [comment]
Clarify in documentation that link index is ignored if invalid
