### ISSUE TITLE
[PE-D][Tester D] Unlink works for company and person who is not linked

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-F11-1/tp#235]
![Screenshot (274).png](https://raw.githubusercontent.com/qiaoen17/ped/main/files/19368f47-9224-4b9f-bc9a-ab3ac36e372e.png)

Previously, `Person 7` was linked to `Internship 6`. 
Command used:
`unlink p/7 i/1`

It unlinks `Person 7` from `Internship 6` even though I intended to unlink `Person 7` from an internship it was never linked to :,)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: qiaoen17/ped#6

**Comment by chengda300** [comment]
Intended behaviour: unlink only takes in either 1 of the 2 pairs. We could specify it clearer in the user guide
